### PR TITLE
fix(#9): Upgraded deps to support latest node version

### LINKED ISSUE #9: Add support to latest nodejs verison
The cli is returning the below error when used with node latest version (v14.15.4)

```bash
 gautam  ~  accessproxy
fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/Users/gautam/.nvm/versions/node/v14.15.4/lib/node_modules/accessproxy/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/gautam/.nvm/versions/node/v14.15.4/lib/node_modules/accessproxy/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/gautam/.nvm/versions/node/v14.15.4/lib/node_modules/accessproxy/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Upgraded deps to support latest node version
fixes: #9

### CODE REVIEW

**Comment by aksgupta14** [comment]
@gautamkrishnar I would suggest you to please take a look at spandx[1]. It was built to replace accessproxy.

[1]https://www.npmjs.com/package/spandx

**Comment by gautamkrishnar** [comment]
@aksgupta14 thanks alot for suggestion, i checked the internal docs but coudnt find any 😄

**Comment by aksgupta14** [comment]
@gautamkrishnar internal docs? You can take a look at the npm page (github too) that should help you with the docs.

**Comment by gautamkrishnar** [comment]
@aksgupta14 yep i got that one. I meant for accessproxy.

**Comment by aksgupta14** [comment]
@gautamkrishnar yeah I don't think that we have any docs for accessproxy but, spandx is supposed to replace accessproxy that's why no one is maintaining this repo.

**Comment by gautamkrishnar** [comment]
yep got it 👍🏻 , closingt this one

**Pull request closed without merging**
